title: Hantas
email: hfl@huangfeilong.com
description: >- # this means to ignore newlines until "baseurl:"
  基于 CSS 逻辑值构建的 CSS 框架。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hfl
github_username:  hfl
paginate: 5
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
